# -*- coding: utf-8 -*-
"""Метод оценки потенциала возвращения функционального назначения советским зданиям.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10y8PsGCe5uFAlcMjqAEVqAegmaNRFo4k

# **Методика оценки потенциала возвращения функционального назначения советским зданиям**
"""

# Установка необходимых библиотек
!pip install pandas openpyxl

import pandas as pd
import numpy as np

# Читаем xlsx файл
df = pd.read_excel('/content/all school.xlsx')
df

"""# Этап: Сбор исходных данных
На данном этапе следует собрать исходные данные для исследуемого объекта.


"""

name="Школа по проекту 2ЛГ-02-2" #Наименование объекта
adress="г. Санкт-Петербург, Промышленная улица, дом 38" #Адрес
functional_zone="Общественно-деловая зона" #Функциональная зона территории
land_use="-" #Режим использования земель
size_land=4663 #Размер земельного участка
area=5866 #Площадь здания
building_area=1543 #Площадь застройки
land_area=941 #Площадь озеленения участка
year_of_commissioning=1965 #Год ввода в эксплуатацию
year_of_termination=2019 #Год прекращения функции образовательной организации
new_feature="Административная" #Новая функция
capacity=600 #Проектная вместимость здания
project_type="Типовой проект школа 2ЛГ-02-2" #Тип проекта
architectural_style="-" #Архитектурный стиль
decoration=False #Наличие исторической отделки
historical_building=False #Историческое здание
technical_condition="Исправное" #Техническое состояние здания
material="Кирпич, железобетон, металл" #Материал наружных стен, перекрытий, кровли
communications=True #Подключение к городским коммуникациям



"""# Этап: сопоставление исходных данных для каждого критерия
Для этой оценки необходимо каждому критерию сопоставить прямые исходные данные (если критерий основан на измеряемых показателях), либо расчетные значения (если критерий требует дополнительных вычислений). Полученные значения затем сравниваются с нормой – установленными нормативными требованиями или эталонными значениями.  Оценка выполняется по такому принципу: 1 балл – данные соответствуют либо выше нормы, 0 баллов – данные не соответствуют норме.
"""

# Преобразование в числа
for col in ['land_size', 'capacity', 'land_area', 'building_area', 'area']:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')

df['capacity'] = df['capacity'].replace(0, np.nan)

# Преобразование годов в числа
for col in ['year_of_commissioning', 'year_of_termination']:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')

"""Архитектурно-планировочные (K1):

Расчет k1_1-k1_9
"""

# Функции проверки

def calculate_k1_1(land_size, capacity):
    """Расчет k1_1 по формуле"""
    if pd.isna(land_size) or pd.isna(capacity):
        return np.nan
    return 1 if land_size >= (capacity * (55 if capacity <= 400 else 65)) else 0

def calculate_k1_2(land_size, land_area, building_area, capacity):
    """Расчет k1_2 по формуле"""
    if any(pd.isna(x) for x in [land_size, land_area, building_area, capacity]):
        return np.nan
    free = land_size - (land_area + building_area + 0.1 * land_size)
    return 0 if free <= 0 else (1 if (free / capacity) > 4 else 0)

def calculate_k1_3(land_size, building_area, land_area, capacity):
    """Расчет k1_3 по формуле: (land_size - (building_area + land_area + 0.1*land_size + 4*capacity)) / capacity"""
    if any(pd.isna(x) for x in [land_size, building_area, land_area, capacity]):
        return np.nan
    if capacity == 0:
        return np.nan
    k1_3_value = (land_size - (building_area + land_area + 0.1 * land_size + 4 * capacity)) / capacity
    return 1 if k1_3_value > 2 else 0

def calculate_k1_4(land_size, building_area, land_area, capacity):
    """Расчет k1_4 по формуле: land_size - (building_area + land_area + 4*capacity + 2*capacity)"""
    if any(pd.isna(x) for x in [land_size, building_area, land_area, capacity]):
        return np.nan
    k1_4_value = land_size - (building_area + land_area + 4 * capacity + 2 * capacity)
    ten_percent = land_size * 0.10
    return 1 if k1_4_value > ten_percent else 0

def calculate_k1_5(new_feature):
    """Проверка типа здания: образовательная, административная, социальная, жилая"""
    if not isinstance(new_feature, str):
        return 0
    allowed_types = ['образовательная', 'административная', 'социальная', 'жилая']
    return 1 if new_feature.strip().lower() in allowed_types else 0

def calculate_k1_6(area, capacity):
    """Расчет k1_6: area / capacity"""
    if any(pd.isna(x) for x in [area, capacity]):
        return np.nan
    if capacity == 0:
        return np.nan
    k1_6_value = area / capacity
    return 1 if k1_6_value >= 2.5 else 0

def calculate_k1_7(k1_7_value):
    """k1_7 берется из исходных данных"""
    return k1_7_value

def calculate_k1_8(new_feature):
    """Проверка типа здания: административная, торговая, социальная, культурная"""
    if not isinstance(new_feature, str):
        return 0
    allowed_types = ['административная', 'торговая', 'социальная', 'культурная']
    return 1 if new_feature.strip().lower() in allowed_types else 0

def calculate_k1_9(land_size, building_area, land_area, capacity):
    """Расчет k1_9: land_size - (building_area + land_area + 4*capacity + 2*capacity + 0.1*land_size)"""
    if any(pd.isna(x) for x in [land_size, building_area, land_area, capacity]):
        return np.nan
    k1_9_value = land_size - (building_area + land_area + 4 * capacity + 2 * capacity + 0.1 * land_size)
    ten_percent = land_size * 0.10
    return 1 if k1_9_value > ten_percent else 0

# Определяем столбец с типом здания (new_feature)
building_col = None
for col in ['new_feature', 'building_type', 'type', 'тип_здания']:
    if col in df.columns:
        building_col = col
        break

# Словарь с расчетами
k1_calc = {
    'k1_1': lambda x: calculate_k1_1(x.get('land_size'), x.get('capacity')),
    'k1_2': lambda x: calculate_k1_2(x.get('land_size'), x.get('land_area'), x.get('building_area'), x.get('capacity')),
    'k1_3': lambda x: calculate_k1_3(x.get('land_size'), x.get('building_area'), x.get('land_area'), x.get('capacity')),
    'k1_4': lambda x: calculate_k1_4(x.get('land_size'), x.get('building_area'), x.get('land_area'), x.get('capacity')),
    'k1_6': lambda x: calculate_k1_6(x.get('area'), x.get('capacity')),
    'k1_9': lambda x: calculate_k1_9(x.get('land_size'), x.get('building_area'), x.get('land_area'), x.get('capacity')),
}

# Выполняем расчеты
for col, func in k1_calc.items():
    df[col] = df.apply(func, axis=1)

# Расчет k1_5 и k1_8 (на основе new_feature)
if building_col:
    df['k1_5'] = df[building_col].apply(calculate_k1_5)
    df['k1_8'] = df[building_col].apply(calculate_k1_8)

"""Социально-экономические (K2)"""

# K2_4: land_area > 20% от land_size
def check_k2_4(land_area, land_size):
    if pd.isna(land_area) or pd.isna(land_size):
        return np.nan
    return 1 if land_area > land_size * 0.20 else 0

df['k2_4'] = df.apply(lambda x: check_k2_4(x.get('land_area'), x.get('land_size')), axis=1)

# K2_5: функциональная зона (0 для П, СЗЗ, ВО, ООТ, иначе 1)
def check_k2_5(zone):
    if not isinstance(zone, str):
        return 0
    return 0 if zone.strip().upper() in ['П', 'СЗЗ', 'ВО', 'ООТ'] else 1

df['k2_5'] = df['functional_zone'].apply(check_k2_5) if 'functional_zone' in df.columns else 0

# K2_9: техническое состояние (1 для исправное, работоспособное)
def check_k2_9(condition):
    if not isinstance(condition, str):
        return 0
    return 1 if condition.strip().lower() in ['исправное', 'работоспособное'] else 0

df['k2_9'] = df['technical_condition'].apply(check_k2_9) if 'technical_condition' in df.columns else 0

"""Инженерно-технические (K3):"""

def check_k3_2(material_string):
    """
    Проверяет критерий k3_2:
    1 - если строка НЕ содержит слово "дерево" (и его производные)
    0 - если строка содержит слово "дерево" (деревянные, деревянное и т.д.)
    """
    if pd.isna(material_string):        return np.nan
    if not isinstance(material_string, str):
        return 0

    material_string_lower = material_string.lower()

    # Проверяем наличие слова "дерево" или его производных
    tree_keywords = ['дерево', 'деревян', 'деревянный', 'деревянная', 'деревянное', 'деревянные']

    for keyword in tree_keywords:
        if keyword in material_string_lower:
            return 0  # Если есть дерево - возвращаем 0


# K3_4: инженерное оборудование
def check_k3_4(comm):
    """
    Проверяет критерий k3_4:
    1 - если значение равно "Подключено"
    0 - для всех остальных значений
    """
    if pd.isna(comm):
        return 0
    if isinstance(comm, str) and comm.strip() == "Подключено":
        return 1
    return 0
#ПЕРЕЗАПИСЬ k3_4 (на основе столбца 'communications')
if 'communications' in df.columns:
    # ПРЯМО ПЕРЕЗАПИСЫВАЕМ существующий столбец k3_4
    df['k3_4'] = df['communications'].apply(check_k3_4)

# K3_5: техническое состояние
def check_k3_5(condition):
    if not isinstance(condition, str):
        return 0
    return 1 if condition.strip().lower() in ['исправное', 'работоспособное'] else 0

df['k3_5'] = df['technical_condition'].apply(check_k3_5) if 'technical_condition' in df.columns else 0

""" Историко-культурные (K4):"""

# K4_1: год ввода 1917-1957
def check_k4_1(year):
    if pd.isna(year):
        return np.nan
    return 1 if 1917 <= year <= 1957 else 0

df['k4_1'] = df['year_of_commissioning'].apply(check_k4_1) if 'year_of_commissioning' in df.columns else np.nan

# K4_4: наличие архитектурного стиля
def check_k4_4(value):
    """
    Проверяет критерий k4_4:
    1 - если значение есть (не пустое, не NaN, не None)
    0 - если значения нет
    """
    if pd.isna(value):
        return 0
    if isinstance(value, str) and value.strip() == '':
        return 0
    return 1

# ПЕРЕЗАПИСЫВАЕМ существующий столбец k4_4
if 'architectural_style' in df.columns:
    # Прямо перезаписываем столбец k4_4
    df['k4_4'] = df['architectural_style'].apply(check_k4_4)

# K4_8: отделка = "Да"
def check_k4_8(value):
    if pd.isna(value):
        return 0
    return 1 if isinstance(value, str) and value.strip().lower() == 'да' else 0

df['k4_8'] = df['decoration'].apply(check_k4_8) if 'decoration' in df.columns else 0

# K4_10: срок службы >= 30 лет
def check_k4_10(end, start):
    if pd.isna(end) or pd.isna(start):
        return np.nan
    return 1 if (end - start) >= 30 else 0

if 'year_of_termination' in df.columns and 'year_of_commissioning' in df.columns:
    df['k4_10'] = df.apply(lambda x: check_k4_10(x['year_of_termination'], x['year_of_commissioning']), axis=1)
else:
    df['k4_10'] = np.nan

# K4_14: наличие типа проекта
df['k4_14'] = df['project_type'].apply(check_k4_4) if 'project_type' in df.columns else 0

# K4_15: землепользование (0 для ОЗ, 1 для остальных)
def check_k4_15(value):
    if pd.isna(value):
        return 1
    return 0 if isinstance(value, str) and value.strip().upper() == 'ОЗ' else 1

df['k4_15'] = df['landuse'].apply(check_k4_15) if 'landuse' in df.columns else 1

"""# Расчет суммарного бала для каждой категории критериев:"""

# Определяем списки показателей для каждой категории
k1_cols = ['k1_1', 'k1_2', 'k1_3', 'k1_4', 'k1_5', 'k1_6', 'k1_7', 'k1_8', 'k1_9']
k2_cols = ['k2_1', 'k2_2', 'k2_3', 'k2_4', 'k2_5', 'k2_6', 'k2_7', 'k2_8', 'k2_9']
k3_cols = ['k3_1', 'k3_2', 'k3_3', 'k3_4', 'k3_5', 'k3_6']
k4_cols = ['k4_1', 'k4_2', 'k4_3', 'k4_4', 'k4_5', 'k4_6', 'k4_7', 'k4_8',
           'k4_9', 'k4_10', 'k4_11', 'k4_12', 'k4_13', 'k4_14', 'k4_15', 'k4_16', 'k4_17']

# Функция для расчета среднего (сумма / количество)
def calculate_i(df, columns, divisor):
    existing = [col for col in columns if col in df.columns]
    if existing:
        # Заменяем NaN на 0 для суммирования
        return df[existing].fillna(0).sum(axis=1) / divisor
    else:
        return np.nan

# Расчет i
df['i_1'] = calculate_i(df, k1_cols, 9)
df['i_2'] = calculate_i(df, k2_cols, 9)
df['i_3'] = calculate_i(df, k3_cols, 6)
df['i_4'] = calculate_i(df, k4_cols, 17)

"""Общий балл вычисляется по формуле:"""

#df = pd.read_excel('/content/all school_2.xlsx')

# Расчет общего балла I
df['I'] = df['i_1'] + df['i_2'] + df['i_3'] + df['i_4']

# Категории для I
def get_category(score):
    if score >= 3.0:
        return 'Высокий'
    elif score >= 2.0:
        return 'Средний'
    elif score >= 1.0:
        return 'Низкий'
    else:
        return 'Очень низкий'

df['I_category'] = df['I'].apply(get_category)

# Сохранение
df.to_excel('/content/all school_обновленный.xlsx', index=False)
print("\n✅ Файл сохранен с общим баллом I!")

"""# Перевод в GEOJSON:"""

import pandas as pd
import json

df = pd.read_excel('/content/all school_2.xlsx')

# Функция для парсинга координат
def parse_coordinates(coord_str):
    if pd.isna(coord_str):
        return None
    # Ожидаем формат: "59.938784, 30.314997"
    parts = str(coord_str).replace('[', '').replace(']', '').split(',')
    if len(parts) >= 2:
        try:
            lat = float(parts[0].strip())
            lon = float(parts[1].strip())
            return [lon, lat]  # GeoJSON: [долгота, широта]
        except:
            return None
    return None

# Создаем GeoJSON
features = []
for idx, row in df.iterrows():
    coords = parse_coordinates(row.get('coordinate'))
    if coords:
        feature = {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": coords
            },
            "properties": row.dropna().to_dict()
        }
        features.append(feature)

geojson = {
    "type": "FeatureCollection",
    "features": features
}

# Сохраняем
with open('здания_спб.geojson', 'w', encoding='utf-8') as f:
    json.dump(geojson, f, ensure_ascii=False, indent=2)

